### ISSUE TITLE
Synchronous error when entering the Great Wall Wonder

### ISSUE THREAD

**Issue by DiegoGW** [gskinnerTeam/flutter-wonderous-app#103]
**Steps to reproduce**

1. Get latest wonderous code: git clone https://github.com/gskinnerTeam/flutter-wonderous-app.git (as a reference this is the latest commit at the time this issue was found: d369891 (HEAD -> main, origin/main, origin/HEAD) Remove unused deps and imports, restore intl pkg to avoid linter warnings)
2. Open the ios workspace in Xcode
3. Run the app in iPhone 14Pro simulator with iOS 17
4. Enter the Great Wall
5. Check the log: 
```
Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}

Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
```

**Expected results**

This error should not be logged after The Great Wall Wonder is entered

**Actual results**

After Wonderous enters this error is logged:
```
Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}

Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
```

**Code sample**

git clone https://github.com/gskinnerTeam/flutter-wonderous-app.git

**Screenshots or Video**

<img width="1174" alt="Screenshot 2023-08-30 at 10 14 35 PM" src="https://github.com/gskinnerTeam/flutter-wonderous-app/assets/11681325/134ae702-487d-43b8-87b5-1388919d8ff2">

**Flutter Doctor output**
[✓] Flutter (Channel master, 3.14.0-12.0.pre.117, on macOS 13.5 22G74
    darwin-arm64, locale en-US)
    • Flutter version 3.14.0-12.0.pre.117 on channel master at
      /Users/diegogawenda/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b89fce108 (31 minutes ago), 2023-08-30 12:49:56 -0700
    • Engine revision 31d5662dcb
    • Dart version 3.2.0 (build 3.2.0-122.0.dev)
    • DevTools version 2.26.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/diegogawenda/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/diegogawenda/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/diegogawenda/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 15A5229m
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.

**Comment by esDotDev** [comment]
Seems like this must be an issue with the flutter SDK or Xcode? Not sure what we could do to address it.
