### ISSUE TITLE
Google Maps plugin throwing errors

### ISSUE THREAD

**Issue by esDotDev** [gskinnerTeam/flutter-wonderous-app#110]
Seeing this error when publishing on Web:
```
The following JSNoSuchMethodError was thrown building GoogleMap(dirty, dependencies:
[Directionality], state: _GoogleMapState#f97b9):
TypeError: Cannot read properties of undefined (reading 'maps')

The relevant error-causing widget was:
  GoogleMap
  GoogleMap:file:///C:/_dev/gskinner/flutter_wonders_app/lib/ui/screens/editorial/widgets/_scrolling_content.dart:249:32
```

Causes the maps to not render:
![image](https://github.com/gskinnerTeam/flutter-wonderous-app/assets/736973/97b596fa-ab04-4843-acde-de4d3f1fcd75)

**Comment by ditman** [comment]
The Google Maps JS SDK must be loaded manually in the index.html of the page for maps to render (also, an API key for web is probably needed).

See this:

https://pub.dev/packages/google_maps_flutter#web

**Comment by esDotDev** [comment]
Thanks! Should've read the docs I guess :p

**Comment by ditman** [comment]
Jeez, didn't mean to sound like an asshole, I got a link to the "web" list of errors and was trying to unblock what I could ASAP, my apologies for the tone  😅
