### ISSUE TITLE
FullScreenVideoViewer - Back button becomes unclickable on web

### ISSUE THREAD

**Issue by esDotDev** [gskinnerTeam/flutter-wonderous-app#111]
On web, the back button becomes unclickable despite being layered on top of the youtube iframe. It seems the iframe is always absorbing the clicks and ignoring flutters display list sorting order.

We could mitigate this by adding some top-padding when on the web platform, but will log this for now in hopes of a better solution:

https://github.com/gskinnerTeam/flutter-wonderous-app/assets/736973/d0dee3ac-3293-4cb0-8332-8270e9d8f47d

**Comment by ditman** [comment]
In order to fix this, the back button can be [wrapped in `package:pointer_interceptor`](https://www.pub.dev/packages/pointer_interceptor), so mouse events don't get lost in the underlying platform view.

**Comment by esDotDev** [comment]
Perfect that works! Ty :)
