### ISSUE TITLE
Menu tiles graphics not clipping on iOS app in large window

### ISSUE THREAD

**Issue by jaredbell** [gskinnerTeam/flutter-wonderous-app#116]
Some of the graphics inside the square menu tiles aren't respecting the corner radius set once the screen is resized. 

When small, corners are fine. > Expand to larger, near full screen desktop sizes and the issue appears.

<img width="389" alt="Screenshot 2023-09-07 at 3 08 11 PM" src="https://github.com/gskinnerTeam/flutter-wonderous-app/assets/7093485/bb7b212c-fd75-42fa-b19d-2461b933690a">

https://github.com/gskinnerTeam/flutter-wonderous-app/assets/7093485/b17cad95-a219-4a5e-b6f7-9827bbf11ea4

**Comment by esDotDev** [comment]
Fixed in https://github.com/gskinnerTeam/flutter-wonderous-app/commit/4d5347013c4c9ec3d36897ab0bd52833a5ae1a74
