### ISSUE TITLE
No factory registered log when searching artifacts

### ISSUE THREAD

**Issue by DiegoGW** [gskinnerTeam/flutter-wonderous-app#119]
**Steps to reproduce**

1. Get latest version of Wonderous app (This is the log when this issue was created - commit 8a29d6709668980340b1b59c3d3588f123edd4d8 (HEAD -> main, origin/main, origin/HEAD)

Merge: a38f564 6523ec3
Author: Shawn <shawn@gskinner.com>
Date:   Mon Sep 11 10:01:33 2023 -0600

    Merge pull request #115 from jonahwilliams/combine_advanced_blends
    
    Reduce SaveLayer count of advanced blends.)

2. Run Wonderous in Xcode 15 RC1 (target: iPhone 15Pro / ios 17)
3. Navigate to the Great Wall (Navigate to: /wonder/greatWall?t=0)
4. Go to artifacts
5. Browse all artifacts
6. Select the search field
7. Check that a dropdown is displayed and a warning message is logged: 
```
AddInstanceForFactory: No factory registered for id <CFUUID 0x600003e93ca0> F8BB1C28-BAE8-11D6-9C31-00039315CD46
132,875 HALC_ProxyIOContext.cpp:1,329 HALC_ProxyIOContext::IOWorkLoop: skipping cycle due to overload
```

**Expected results**
No warning should be logged, after selecting the search field for artifacts

**Actual results**
A warning is being logged, after selecting the search field for artifacts

**Screenshots or Video**
<img width="1261" alt="Screenshot 2023-09-14 at 7 08 24 AM" src="https://github.com/gskinnerTeam/flutter-wonderous-app/assets/11681325/85f973a1-13cd-47b3-bed5-51e308a2cfcf">

**Flutter Doctor output**
[✓] Flutter (Channel master, 3.14.0-14.0.pre.282, on macOS 13.5 22G74 darwin-arm64, locale en-US)
    • Flutter version 3.14.0-14.0.pre.282 on channel master at /Users/diegogawenda/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5243d18e8d (14 hours ago), 2023-09-13 16:33:16 -0400
    • Engine revision 154d6fd601
    • Dart version 3.2.0 (build 3.2.0-140.0.dev)
    • DevTools version 2.27.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/diegogawenda/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/diegogawenda/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/diegogawenda/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • iPhone 15 Pro (mobile) • 3BFEADEA-E755-4F48-8446-0F69B0F059E4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 117.0.5938.62

[✓] Network resources
    • All expected network resources are available.

**Comment by esDotDev** [comment]
It appears this is just a warning that appears when using the simulator: https://stackoverflow.com/a/74540782/463029

If this is a significant issue it should likely be logged in the flutter SDK repo, as we have limited control over the internals of Flutter TextFields.
