### ISSUE TITLE
Can't run app on iOS

### ISSUE THREAD

**Issue by Umigishi-Aoi** [gskinnerTeam/flutter-wonderous-app#12]
When I tried to run the app on my actual iOS device, I got the following error and could not run this app.

``Unhandled Exception: MissingPluginException(No implementation found for method getSupportedModes on channel flutter_display_mode)``

I think , this error is caused by the following code.

/[lib](https://github.com/gskinnerTeam/flutter-wonderous-app/tree/master/lib)/[logic](https://github.com/gskinnerTeam/flutter-wonderous-app/tree/master/lib/logic)/[app_logic.dart](https://github.com/gskinnerTeam/flutter-wonderous-app/blob/master/lib/logic/app_logic.dart#L25)

```dart
    await FlutterDisplayMode.setHighRefreshRate();
```

flutter_displaymode package is only available for Android.
I was able to run this app by commenting out that code.

Isn't it better to add a conditional expression so that that code can only be executed on Android?

**Comment by esDotDev** [comment]
Yes, this conditional check has been added, sorry for the issue.
