### ISSUE TITLE
Usage of provider package in the repository

### ISSUE THREAD

**Issue by sreerajlal** [gskinnerTeam/flutter-wonderous-app#120]
I've been exploring the codebase and noticed that the provider package is listed as a dependency. However, I couldn't immediately identify where it's being used within the application. I'm curious to understand its role and usage in this project.

Could someone point me to the parts of the code where the provider package is utilized? I'd appreciate any insights or explanations.

Thank you for your time and assistance!

**Comment by esDotDev** [comment]
Provider is used in the `WonderIllustrationBuilder` to pass down the builder state to each descendant `IllustrationPiece` just to save some excessive property drilling into the 35 various illustration pieces.
