### ISSUE TITLE
Frame dropping on scroll with iOS local build

### ISSUE THREAD

**Issue by karimafas** [gskinnerTeam/flutter-wonderous-app#123]
Hi team,

Today I noticed significant frame dropping with the scrolling behaviour on one of the SingleChildScrollViews on my local build when I compared it to the AppStore build. For the record, I just cloned the repo, sorted out the signing and built the app in release mode, so this cannot be a result of implementation changes.

**App store build**
https://github.com/gskinnerTeam/flutter-wonderous-app/assets/77198675/d0fdf166-7380-469a-abd9-46f52a9da5cf

**Local build**
https://github.com/gskinnerTeam/flutter-wonderous-app/assets/77198675/42e09cf8-79d8-40c3-bca8-23aed26b8000

I am under the impression that Impeller does all shader compilation at build time, and that it is not required to pre-compile shaders, but the difference in performance leaves me quite perplexed and I am wondering if this is still required. Otherwise, I can't think ogofany other potential differences in the two builds that would result in the scrolling lag. 

Any ideas?

**Comment by karim-touristar** [comment]
Closing this issue as it is being amply discussed in the Flutter repo, i.e. https://github.com/flutter/flutter/issues/134309. For me, downgrading to Flutter 3.13.2 resolved this, as it appears that 2.13.3 regressed around this issue.

**Comment by karim-touristar** [comment]
This issue is being amply discussed in the Flutter repo, i.e. https://github.com/flutter/flutter/issues/134309. For me, downgrading to Flutter 3.13.2 resolved this, as it appears that 2.13.3 regressed around this issue. As far as I'm concerned this can be closed

**Comment by karimafas** [comment]
This issue is being amply discussed in the Flutter repo, i.e. [flutter/flutter#134309](https://github.com/flutter/flutter/issues/134309). For me, downgrading to Flutter 3.13.2 resolved this, as it appears that 2.13.3 regressed around this issue. Closing
