### ISSUE TITLE
Update the website to have a macOS download button

### ISSUE THREAD

**Issue by esDotDev** [gskinnerTeam/flutter-wonderous-app#125]
Modify the text to include macOS, and add a new download button
![image](https://github.com/gskinnerTeam/flutter-wonderous-app/assets/736973/d6b31499-cd5c-4378-9936-4d7d8bb997b2)

**Comment by asaarnak** [comment]
There is now mac os button but it's redirecting to play store.
![image](https://github.com/gskinnerTeam/flutter-wonderous-app/assets/808420/01ce42b5-791a-47d2-971f-a40e49fcf5b0)

**Comment by esDotDev** [comment]
This has been fixed and the updated site deployed.
