### ISSUE TITLE
Mouse horizontal scrolling speed depends on screen size.

### ISSUE THREAD

**Issue by asaarnak** [gskinnerTeam/flutter-wonderous-app#126]
I have MX Master 3 mouse that has dedicated horizontal scroll wheel.
Horizontal scrolling carousel and pages and pictures works, but it's not perfect.
The bigger the screen the more you need to scroll for the page to switch.
When using full screen window QHD 2560x1440 then it's really hard to scroll to the next page.
When resizing window to smallest size then it's easy to scroll pages too fast and skip pages.
Mac OS 14.0
App version: 2.0.16

**Comment by esDotDev** [comment]
Sounds like this would be an issue with the Flutter SDK itself. Can you reproduce using a simple PageView? If so I'd recommend filing an issue with the Flutter SDK and provide the basic reproduction steps.
