### ISSUE TITLE
Web UX: Carousel navigation

### ISSUE THREAD

**Issue by jaredbell** [gskinnerTeam/flutter-wonderous-app#136]
- Add keyboard support for main carousel, so you can use the left-right arrows to navigate the carousel, and down arrow to enter a wonder

- Add physical (left/right) buttons to indicate carousel behavior and allow step through without drag. (include accessible + localized labels for Next/Previous).
![image](https://github.com/gskinnerTeam/flutter-wonderous-app/assets/7093485/247a7459-3035-4a64-8671-2817d2c009cf)

- Enable clickable pagination dots to navigate between wonders

- Add in back (up) button from mobile portrait to web wide, to provide another way to exit a wonder.
![image](https://github.com/gskinnerTeam/flutter-wonderous-app/assets/7093485/f6841365-cba6-422b-a00b-f21c9ce08f5a)

**Comment by esDotDev** [comment]
@jaredbell Should we hide these on iOS/Android?
