### ISSUE TITLE
Web UX: Use mouse scroll to enter/exit wonder

### ISSUE THREAD

**Issue by jaredbell** [gskinnerTeam/flutter-wonderous-app#137]
Currently there is no way to use the trackpad or scrollwheel to navigate into or out of a wonder. A user is forced use a click, hold and drag gesture instead.

This doesn't feel intuitive in either direction. 

On the macOS version of Wonderous, the trackpad simulates touch interactions and is usable for swiping left/right or progressively up into a wonder (see below).

https://github.com/gskinnerTeam/flutter-wonderous-app/assets/7093485/83ac1aca-7e01-4782-b8b7-715591c0c2be

**Comment by esDotDev** [comment]
@jaredbell I tried to add this but can't get it to feel nice. 
* When scrolling UP in the editorial view, it transitions to quickly back to home, which doesn't feel good.
* When scrolling DOWN from home carousel, it can scroll the editorial view as it comes into view, which also doesn't feel nice.

Will leave open for now in case I can find something that works.
