### ISSUE TITLE
Web UX: Add physical buttons to intro steps

### ISSUE THREAD

**Issue by jaredbell** [gskinnerTeam/flutter-wonderous-app#139]
To aid navigation of the intro screens, opt for physical buttons vs. the swipe-only controls retained from touch. _It is assumed a "back" button isn't critical for these steps._

These buttons should also be centered to avoid being too far away from the contents in large window sizes.

Use next + right arrow for first two:
![image](https://github.com/gskinnerTeam/flutter-wonderous-app/assets/7093485/2af87b77-20dc-4a35-8254-2006a967a758)

And Get Started for the final screen:
![image](https://github.com/gskinnerTeam/flutter-wonderous-app/assets/7093485/f225255f-ed02-41c9-9494-6ab69b267d83)

**Comment by esDotDev** [comment]
@jaredbell Vertical space is at a premium in this view as we don't really have a good landscape layout in place. Thoughts on just using some arrows, similar to #136 ?
