### ISSUE TITLE
Web UX: [Esc] key to close overlays

### ISSUE THREAD

**Issue by jaredbell** [gskinnerTeam/flutter-wonderous-app#143]
When navigating in a full-screen sub view, allow the user to exit (go back) by using the [esc] key as a common web shortcut for exiting full screen or modals. Basically, any view that currently has a back arrow ( <- ) or ( x ) button.

The views effect by this would be:

- Full screen photo gallery
- Artifact details and full screen photo viewer
- Artifact search
- Timeline navigator
- Youtube viewer
- Google maps view
- Artifact discovery overlay
- Expanded home menu
- Collection viewer

Note, this behavior is already active for the "about this app" modal.

<img width="1608" alt="Screenshot 2023-10-31 at 3 31 06 PM" src="https://github.com/gskinnerTeam/flutter-wonderous-app/assets/7093485/223da570-f97e-40c1-8c81-3b64e09246a3">
<img width="1608" alt="Screenshot 2023-10-31 at 3 29 58 PM" src="https://github.com/gskinnerTeam/flutter-wonderous-app/assets/7093485/70453676-a532-476e-b394-e6b8f2fb203b">
<img width="1608" alt="Screenshot 2023-10-31 at 3 30 59 PM" src="https://github.com/gskinnerTeam/flutter-wonderous-app/assets/7093485/42cf72db-504d-461f-ada9-10154b1a67b0">

**Comment by esDotDev** [comment]
Just landed this. @jaredbell 
* I turned this on for all back btns by default, 
  * this means that the editorial view now goes back to the wonders_home when escape is pushed.
  * we can exit from the editorial view back to home
