### ISSUE TITLE
Add web analytics

### ISSUE THREAD

**Issue by esDotDev** [gskinnerTeam/flutter-wonderous-app#149]
Add google analytics to track
- traffic
- performance 
  - load times
  - dropped frames

**Comment by esDotDev** [comment]
Update: Attempted to add the firebase analytics pkg to the app, but trying to embed firebase_core broke the build on windows. We rely heavily on windows builds for development and responsive UI testing, so we rolled back that change. 

As an alternative, we added a web-based analytics hook so we can at least measure traffic to the site homepage.

**Comment by kevmoo** [comment]
You can just wire up web analytics in the HTML – zero Dart/Flutter code changes required. Just so we have general traffic data.

**Comment by esDotDev** [comment]
Yep, we did! Mentioned that in the last sentence there

**Comment by esDotDev** [comment]
@kevmoo Any thoughts on how we could track performance analytics? Maybe that's something better measured locally?

**Comment by kevmoo** [comment]
> @kevmoo Any thoughts on how we could track performance analytics? Maybe that's something better measured locally?

Check in "vanilla" analytics for now. We will follow-up with perf tracking!
