### ISSUE TITLE
Desktop UX: keyboard shortcuts

### ISSUE THREAD

**Issue by bartekpacia** [gskinnerTeam/flutter-wonderous-app#162]
I downloaded Wonderous from Mac App Store.

I noticed that it doesn't support common keyboard shortcuts. For example, on this "large image" screen I'd expect the ESC key to go back (i.e. same as clicking the back arrow):

<img width="1423" alt="Screenshot 2024-01-22 at 16 30 15" src="https://github.com/gskinnerTeam/flutter-wonderous-app/assets/40357511/1e89a803-1fd8-4296-aa76-99a7b1494f97">

Additionally, CTRL+TAB could be used to easily switch between tabs on the left sidebar:

<img width="133" alt="Screenshot 2024-01-22 at 16 31 45" src="https://github.com/gskinnerTeam/flutter-wonderous-app/assets/40357511/86d74354-d096-4309-94a5-63ce4847e194">

**Comment by esDotDev** [comment]
Thank's for the report, we have already improved Desktop UX in the current `main` branch and plan to push a new macOS version soon.
