### ISSUE TITLE
Web: App hangs on splash screen on Android

### ISSUE THREAD

**Issue by kevmoo** [gskinnerTeam/flutter-wonderous-app#164]
Tried on SEVERAL different devices.

**Comment by mit-mit** [comment]
I speculate that this is an issue in the splash screen plugin, and suggest we conditionally remove the use of that plugin on web.

**Comment by esDotDev** [comment]
I was able to reproduce this, and according to the debug console in chrome this was an issue calling the `FlutterDisplayMode.setHighRefreshRate` method which is only supported on Android. 

I've deployed the latest version which includes a fix for the platform-check and this method should no longer be called. 

It's loading good over here. Can you check if this is still reproduceable on your end? You may need to clear your cache.

**Comment by kevmoo** [comment]
Confirmed! Thanks so much!
