### ISSUE TITLE
Wasm build deployment.

### ISSUE THREAD

**Issue by ebala96** [gskinnerTeam/flutter-wonderous-app#185]
Can you share the steps of doing wasm build deployment?

Do you use the `dhttp ` package mentioned in the following flutter documentation?
https://docs.flutter.dev/platform-integration/web/wasm#serving-wasm-locally

**Comment by esDotDev** [comment]
Yep, we used the commands shown in the documentation there. Just create the wasm build, navigate to the build folder, run the `dhttpd` command and then open the browser to localhost:8080.
