### ISSUE TITLE
Scroll issues with iPhone 13

### ISSUE THREAD

**Issue by esDotDev** [gskinnerTeam/flutter-wonderous-app#28]
Using iPhone 13 w/ 120fps display, we are seeing some stuttering / jumping around of the native maps view when scrolling.

Hard to see in the video, but you can kinda make it out:

https://user-images.githubusercontent.com/736973/189768405-11cca9df-7ac7-4568-a8d4-f5e94f5ecc0e.MP4

Also, At 0:39 in this video, you can make out some significant stuttering in the fullscreen map view:

https://user-images.githubusercontent.com/736973/189769468-66d2b570-1330-46f8-9469-51f34111f4a1.MP4

**Comment by coolkiecat** [comment]
Me too, on One Plus9RT, There is jank while sliding up and down

**Comment by baimamboukar** [comment]
I was exploring the app and I experienced the same issue!

**Comment by coolkiecat** [comment]
[自动回复]您好，我已收到你的邮件，这是邮箱自动回复

**Comment by coolkiecat** [comment]
[自动回复]您好，我已收到你的邮件，这是邮箱自动回复
