### ISSUE TITLE
In the “browse artifacts” view, keyboard is not dismissable by swiping

### ISSUE THREAD

**Issue by leighajarett** [gskinnerTeam/flutter-wonderous-app#30]
On iOS, I would expect that when you start scrolling on the browse artifacts page after initiating search, the keyboard would be dismissed automatically.

**Comment by esDotDev** [comment]
This seems reasonable to me, @gskinner @jaredbell ?

**Comment by jaredbell** [comment]
Yes that's intuitive, with focus leaving the search field.

**Comment by esDotDev** [comment]
This is implemented and will be present in the next build. Thanks!
