### ISSUE TITLE
About performance optimization

### ISSUE THREAD

**Issue by paintingStyle** [gskinnerTeam/flutter-wonderous-app#35]
hey, this app is awesome, especially the animation experience on iOS devices. 

 I saw that you have optimized the performance in the last few updates. I would like to know your optimization experience, how to make the application performance better, can you share, such as how to make the animation smoother, you have encountered the first time the SKSL animation freezes  Question, do you do sksl preheating?  

Looking forward to your reply

**Comment by esDotDev** [comment]
Most of the improvement are just re-building with the latest version of impeller which has ongoing perf improvements.
https://github.com/gskinnerTeam/flutter-wonderous-app#impeller-rendering-layer

No need to cache SKSL anymore, it just works!
