### ISSUE TITLE
Clone CO from Github throws Following Errors

### ISSUE THREAD

**Issue by meltro21** [gskinnerTeam/flutter-wonderous-app#39]
Flutter Version 3.0.5
Dart.                  2.17.6

When downloaded the code from Github, it shows couple of Errors.
**Error 1**
In "lib->logic->common->retry_image.dart" loadBuffer function throws an error.
<img width="1419" alt="Screenshot 2022-10-03 at 4 54 09 PM" src="https://user-images.githubusercontent.com/75183736/193571615-7ea5496b-d0ac-4705-a6bc-be320e68e3b9.png">
**Error 2**
In "lib->logic->common->wallpaper_logic.dart" unit8List shows error. 

<img width="1463" alt="Screenshot 2022-10-03 at 5 00 46 PM" src="https://user-images.githubusercontent.com/75183736/193572182-43979fec-7e3c-476b-857f-16757ffec6b5.png">
**Fix Error 2**
Hover on unit8List and import the "dart:typed_data"

**Error 3**
In "lib->logic->ui->common->app_backdrop.dart" clampDouble method is not recognised.
  
<img width="1463" alt="Screenshot 2022-10-03 at 5 10 58 PM" src="https://user-images.githubusercontent.com/75183736/193573593-d8370edc-cdda-44e7-a20c-edc92848391d.png">

**Fix Error 3**

<img width="1454" alt="Screenshot 2022-10-03 at 5 07 07 PM" src="https://user-images.githubusercontent.com/75183736/193573639-a69b5617-6d4d-4272-8b1e-efd182371de3.png">

**Comment by esDotDev** [comment]
As mentioned in the readme this project needs to be run on either `beta` or `master`. Try:
`flutter channel beta`
