### ISSUE TITLE
Not running in 120hz on Oneplus 9 pro

### ISSUE THREAD

**Issue by RobertBrunhage** [gskinnerTeam/flutter-wonderous-app#5]
Gave the app a try but it doesn't seem to push the 120fps and feels quite sluggish compared to my other apps.

**Comment by esDotDev** [comment]
Thanks for the report! Can you try branch [feature-request-max-fps](https://github.com/gskinnerTeam/flutter-wonderous-app/tree/feature-request-max-fps) and see if it's better?

**Comment by RobertBrunhage** [comment]
@esDotDev Can probably try it during the weekend, I am 99% sure this will work though. Have had to do the same change myself to get 120fps support.

**Comment by esDotDev** [comment]
Ok, we'll merge this into the main app since it seems like a good practice anyways. Please let us know how it goes!
