### ISSUE TITLE
Minimum system requirements ?

### ISSUE THREAD

**Issue by jjboy91** [gskinnerTeam/flutter-wonderous-app#51]
Hello,
I tried building the app on an iPad Mini 2 with Impeller enabled.
When monitoring in dev tools I am seeing a lot of performances issues.

Is my device too old ?

Thanks

![Capture d’écran 2022-12-05 à 10 49 41](https://user-images.githubusercontent.com/19731153/205606647-04f837e7-8c2a-4381-a904-f2d4d48fdc39.png)

**Comment by esDotDev** [comment]
Our understanding is that this is a known issue w/ Impeller and should improve in the future. As the flutter team implements the android version, there will be a lot of focus on lower-spec devices, and that will also help speed up the older iOS devices.
