### ISSUE TITLE
Handle even number as gridSize in PhotoGallery

### ISSUE THREAD

**Issue by NohchoBx** [gskinnerTeam/flutter-wonderous-app#52]
Hi,

First of all thanks for sharing this code, the app is awesome! 
Actually I'm trying to implement the PhotoGallery feature. I have a 36 images that I want to display by setting the ``` _gridSize ``` at 6 so  ``` _imgCount ``` fits perfectly with the number of images that I have.  But I'm getting some trouble with handling the Offset returned by  the  ```_calculateCurrentOffset(double padding, Size size)``` method. As you can see here the Offset isn't right. 

![photo_2022-12-07_02-40-48](https://user-images.githubusercontent.com/86976892/206066825-dd3b3d6c-92c8-40cc-9283-4d0b2eeaab40.jpg)

The offset seems to be correct only when the ``` _gridSize ``` is an odd number.
Does someone have any suggestion to get the right Offset? 
Thanks.

**Comment by esDotDev** [comment]
The logic is assumes odd sized cols and rows because we wanted to have a "center" item.

To work with even numbers, you should just need to tweek the logic inside of `_calculateCurrentOffset` to act slightly differently.
