### ISSUE TITLE
White Box on Timeline

### ISSUE THREAD

**Issue by esDotDev** [gskinnerTeam/flutter-wonderous-app#53]
What is normally a white border with vertical dashed line, is rendering as a white square, only when using Impeller on a real device.

It seems to be caused by the simple: 
```dart
Container(
  decoration: BoxDecoration(border: Border.all(color: borderColor))
)
```

![image](https://user-images.githubusercontent.com/736973/206556717-f7ea7bf9-34a6-413c-bb11-41bef96cbf7c.png)

Should be: 
![image](https://user-images.githubusercontent.com/736973/206556605-603d5b3d-d197-46fa-ba2b-35a7aedff465.png)

**Comment by bdero** [comment]
This should be fixed when https://github.com/flutter/engine/pull/38146 lands.
