### ISSUE TITLE
Wonderous build error with android MainActivity.kt

### ISSUE THREAD

**Issue by khsbory** [gskinnerTeam/flutter-wonderous-app#55]
I tried to test flutter with wonderous latest commit.
My flutter channel is beta and latest version.
But once I build this app with android studio, below errors are shown.
How can I fix this error?
Thank you.
e: E:\project\flutter\flutter-wonderous-app\android\app\src\main\kotlin\com\gskinner\flutter\wonders\MainActivity.kt: (5, 7): Redeclaration: MainActivity
e: E:\project\flutter\flutter-wonderous-app\android\app\src\main\kotlin\com\gskinner\wonders\MainActivity.kt: (8, 7): Redeclaration: MainActivity

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by esDotDev** [comment]
Can you try the latest version and see if you still have issues?
