### ISSUE TITLE
build failed on latest beta version of flutter 3.7.0-1.1.pre

### ISSUE THREAD

**Issue by ximmyxiao** [gskinnerTeam/flutter-wonderous-app#56]
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/3937940/207531230-e1843755-75dd-4a2f-9f25-f79c8500d5dc.png">

**Comment by ndrsgalvis** [comment]
have the same issue width ListenableBuilder ...

**Comment by bartekpacia** [comment]
Doesn't work on Flutter 3.7.

**Comment by esDotDev** [comment]
Current recommended version is 3.13.x (latest stable)
