### ISSUE TITLE
[Android] [ui] Red artefacts while rendering collection placeholders 

### ISSUE THREAD

**Issue by mariopepe** [gskinnerTeam/flutter-wonderous-app#57]
App version: 1.9.5 (downloaded from the Play Store)
Device: Samsung Galaxy A13
Android version: 12 (latest for this device)
One UI Core version 4.1 (latest for this device)
Google Play system update: October 1 2022 (latest for this device)

in the "Collection" page, red artefacts are visible around the borders of the svgs (or the images, not sure the format) that serve as placeholders, see the screenshot in full screen to understand:

<img src="https://user-images.githubusercontent.com/14803862/208084122-9ef9b4a5-31bc-49f5-8dda-23695f41c3b2.jpg" data-canonical-src="https://user-images.githubusercontent.com/14803862/208084122-9ef9b4a5-31bc-49f5-8dda-23695f41c3b2.jpg" width="300" />

**Comment by esDotDev** [comment]
We can not reproduce here. Can you try disabling the blend mode on the image and see if that is that cause?

I wonder if it is some issues with the gpu? Looks like you are running a Exynos 850 chipset, our test device is a SM7125 Snapdragon.
