### ISSUE TITLE
Poor image filtering when using impeller on iOS

### ISSUE THREAD

**Issue by esDotDev** [gskinnerTeam/flutter-wonderous-app#69]
Small PNG icon images are not being filtered as nicely as they were before:

Impeller on right:
![image](https://user-images.githubusercontent.com/736973/214348087-3593b5f9-3c8b-44f6-ab7e-adf166ce3e0e.png)

To view this, run the app w/ Impeller enabled, and open the "home menu". Observe any of the 3 icon buttons along the bottom of the screen:

![image](https://user-images.githubusercontent.com/736973/214348707-47360b2d-7e5a-4610-b246-198215defdb6.png)

**Comment by bdero** [comment]
This will be fixed with https://github.com/flutter/engine/pull/39483.
