### ISSUE TITLE
Stuttering on iOS

### ISSUE THREAD

**Issue by dkbast** [gskinnerTeam/flutter-wonderous-app#7]
Hi - the app looks amazing!
One thing I noticed, is that the "text on image" section e.g "the longest man-made structure in the world" is stuttering when scrolling slowly over it, especially when scrolling up and down on it to "play" with the animation.
I tested this on an iPhone 12mini.

**Comment by gskinner** [comment]
Thanks for the report. This is due to the blend mode on that section, which isn't fully optimized in the early access Impeller engine (which we are using in the iOS version). The Flutter team is aware of this, and we hope to have an improved version in the stores before too long.

**Comment by hellohuanlin** [comment]
The table on the last tab is also stuttering when scroll. Tested on iPhone 12.

**Comment by gskinner** [comment]
@hellohuanlin — Thanks for the additional info. Are you seeing this with the event list that scrolls up over the blurred image of the wonder?

If so, that's the other place we are aware of a little bit of a slow down, related to the animated blur in the (early access) Impeller engine. You should see the scroll become nice and smooth once the blurred header is completely hidden behind the list. This should also improve as the Impeller engine continues to be refined and optimized.

**Comment by Dirklectisch** [comment]
Came here to report both of these. Great job on the app and looking forward to seeing these two cases become more smooth. I would love to use this app as a showcase for what Flutter can do.

**Comment by esDotDev** [comment]
This should be better in version 1.0.3 or later. Please let us know!

**Comment by Dirklectisch** [comment]
This is a big improvement for sure. I still experience light stuttering on the timeline tab with the blurred header. I'm using an iPhone 12 Pro. All in all I'm happy with the progress that is being made on this.

**Comment by Dirklectisch** [comment]
Happy to report that performance on `1.9.6` is significantly better.
