### ISSUE TITLE
Mac Desktop version doesn't show Images or Artifacts

### ISSUE THREAD

**Issue by androticus** [gskinnerTeam/flutter-wonderous-app#71]
I just built Wonderous, and ran it successfully on my Pixel 6 device, and the iPhone 14 Pro Max emulator.
But when I built and ran it for MacOS Desktop, and you click on either the Images or Artifacts icon, it just shows the images as circle-X.
Mac OS Ventura 13.0.1, on Intel (MBP late 2017 model)
Flutter 3.7.0
Android Studio Electric Eel | 2022.1.1

**Comment by esDotDev** [comment]
macOS was missing network permissions, but it's fixed now. Thanks for the report!
