### ISSUE TITLE
 wonders depends on intl ^0.18.0, version solving failed.

### ISSUE THREAD

**Issue by gratien-humaapi** [gskinnerTeam/flutter-wonderous-app#76]
Hello. I hope you are well.

I get this error message when I do "flutter pub get"
![Screenshot 2023-03-09 174213](https://user-images.githubusercontent.com/86977154/224092771-7e803b9e-6e26-4330-8fc0-fa7601070721.png)

**Comment by zyllus17** [comment]
Hey @gratien-humaapi change the `intl ^0.18.0` to `intl ^0.17.0` and it will fix the issue.

**Comment by gratien-humaapi** [comment]
Ok thanks.
