### ISSUE TITLE
Artifacts/glitches during transition

### ISSUE THREAD

**Issue by esDotDev** [gskinnerTeam/flutter-wonderous-app#8]
When building with commit `8de361154d3c76c5f784cb887cc431084d280fb8 ` we're seeing artifacting/glitching when opening the home menu, or navigating to the timeline:

https://user-images.githubusercontent.com/736973/187732568-42855cea-d7a7-4318-90ae-35d0d8729d3a.MP4

**Comment by bdero** [comment]
Fix for this issue: https://github.com/flutter/engine/pull/35847
