### ISSUE TITLE
Compilation error with Flutter 3.10

### ISSUE THREAD

**Issue by aneeskA** [gskinnerTeam/flutter-wonderous-app#87]
Error
```
{ ...
	"message": "Undefined class 'Display'.\nTry changing the name to the name of an existing class, or creating a class with the name 'Display'.",
	"source": "dart",
	"startLineNumber": 88,
	"startColumn": 3,
	"endLineNumber": 88,
	"endColumn": 10
},{
 ...
	"message": "The getter 'displays' isn't defined for the type 'PlatformDispatcher'.\nTry importing the library that defines 'displays', correcting the name to the name of an existing getter, or defining a getter or field named 'displays'.",
	"source": "dart",
	"startLineNumber": 88,
	"startColumn": 54,
	"endLineNumber": 88,
	"endColumn": 62
}]
```

<img width="1159" alt="image" src="https://github.com/gskinnerTeam/flutter-wonderous-app/assets/514419/1eb74a42-87aa-4d1c-b4fe-19eec1e25151">

I am on main branch with 
```
commit c2be9688db680199edc0d49b1d536ad8bf176987 (HEAD -> main, origin/main, origin/HEAD)
Author: Shawn <shawn@gskinner.com>
Date:   Thu May 11 10:55:34 2023 -0600

    Fix nav-rail check
```
as the commit.

Flutter 3.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f92f44110e (2 days ago) • 2023-06-01 18:17:33 -0500
Engine • revision 2a3401c9bb
Tools • Dart 3.0.3 • DevTools 2.23.1

**Comment by uc-vrm** [comment]
I have the same issue too.

**Comment by nmnclk** [comment]
Same

**Comment by Madhan-Rkv-10** [comment]
I have same Issue

**Comment by bipboy** [comment]
In 3.10 the window singleton is [deprecated](https://docs.flutter.dev/release/breaking-changes/window-singleton). You have to use FlutterView instead.

// app_logic.dart
`FlutterView get display => PlatformDispatcher.instance.views.first;`

**Comment by aneeskA** [comment]
This solved the problem at that line. But `display.size` still had issues. So I had to do `display.physicalSize` to fix them.

**Comment by huycozy** [comment]
I still see this issue on Flutter stable 3.10.6 and main branch of this repo. Applying the suggestions above can solve this but I wonder why there is no PR for this.
