### ISSUE TITLE
Issues with Web build target

### ISSUE THREAD

**Issue by esDotDev** [gskinnerTeam/flutter-wonderous-app#91]
We are seeing a number of issues when deploying to the web platform.

Functionality
* [ ] Youtube thumbnail img is not displaying properly (CORS error)
* [ ] MET images are not loading correctly (CORS error)
* [ ] Maps plugin is not displaying "_Cannot Read Properties Of Undefined (Reading ‘Maps’)_"

Performance
* [ ] Dropped frames on the main wonders carousel when switching wonders
* [ ] Dropped frames on the Artifacts Carousel view when switching artifacts 
* [ ] Dropped frames in the Search Artifacts view when the window is expanded to full screen
* [ ] Dropped frames in the global timeline view when scrolling

**Comment by mit-mit** [comment]
Hi @esDotDev can you clarify on the performance issues what mode you ran the web app with?

I tried to run this myself (just cloned this repo + ran `flutter create . --platform wwb`), and while I do see some drops in debug builds with `flutter run -d chrome` that is not too surprising for a debug build. When in profile mode (`flutter run --profile -d chrome`) it seems to run with no major perf issues with Flutter 3.13?

**Comment by mit-mit** [comment]
I was seeing close to 100fps, but I could not be looking carefully enough. If you see anything less than 60 on anything in either profile or release, details most welcome!

**Comment by esDotDev** [comment]
Did a bit more testing today, overall it feels quite nice, but still seeing the odd frame drop when first loading up the Wonders carousel, or when transitioning into the Detaills view for a selected wonder: 
![chrome_FDWcYqpwcs](https://github.com/gskinnerTeam/flutter-wonderous-app/assets/736973/6c1d07d3-f06e-4f55-b734-886b97ae59c2)

Also a cpl when opening the WondersHomeMenu and Timeline views:
![chrome_8PtyREtZjj](https://github.com/gskinnerTeam/flutter-wonderous-app/assets/736973/0d4b677a-7e52-4d68-bb04-2bee5c3299ea)

These don't feel too bad visually though, seems like it's quite a bit better than last time we tested.

Also seeing poor performance on the Artifact Search screen, but that seems to be caused by some network load errors being spammed to the console, so that would probably be fixed once we resolve the loading issues.

**Comment by mit-mit** [comment]
cc @kevmoo
