### ISSUE TITLE
[Accessibility] - Not possible to navigate back on the artifacts screen using VoiceOver

### ISSUE THREAD

**Issue by DiegoGW** [gskinnerTeam/flutter-wonderous-app#93]
**Actual behavior:**     
- In the Browse Artifacts screen is not possible to select the back arrow, because it gets overlapped by the global timeline header element. You need to close the app because it seems there is no work around for this situation.
- Same issue happens in Global Timeline screen - back arrow gets overlapped and is not accessible

**Environment:** iPhone 14 Pro / iOS 16.4.1 / Wonderous 2.0.13

**Replication steps:**
Scenario Browse Artifacts:
1. Turn on VoiceOver
2. Open Wonderous app
3. Select the Great Wall
4. Go to artifacts menu item at the bottom
5. Select Browse Artifacts button
6. Try to tap the back arrow button

Scenarios Global Timeline:
4.1 Go to timeline menu item at the bottom
4.2 Open Global Timeline
6.1 Try to tap the back arrow button

**Expected behavior:**
It should be possible to select the back arrow in Global Timeline and Browse Artifacts screens

Videos/Snapshots:

- https://drive.google.com/file/d/1r6eNhs4bMvfLyiZgeQMSM4FX0UVQnutL/view?usp=sharing
- https://drive.google.com/file/d/1csqh9mXnkHjnUaJ_eRzUFEthoAB0xARG/view?usp=sharing

![Global Timeline](https://github.com/gskinnerTeam/flutter-wonderous-app/assets/11681325/6ad5a3f2-351e-4423-b497-5772c606dc96)
![Browse Artifacts](https://github.com/gskinnerTeam/flutter-wonderous-app/assets/11681325/46e76057-03f9-4703-bc60-5ae59cb283f1)

**Comment by leighajarett** [comment]
@esDotDev could you take a look at this?

**Comment by esDotDev** [comment]
This has been fixed in ce767b71, can you confirm it's working good on your end?

**Comment by DiegoGW** [comment]
Thanks @esDotDev!

Validated in Wonderous version 2.0.17 running the replication steps of the description.
Environments tested: iphone 14 pro + ios 16.6 and pixel 6 + api 33

Video [link](https://drive.google.com/file/d/11fAaiFUcrEZq4O_0b_AmZS0pqcsv1Xoa/view?usp=sharing) confirming the fix.

**Comment by DiegoGW** [comment]
Marking this issue as done.

**Comment by leighajarett** [comment]
Thanks both!
