### ISSUE TITLE
[Curiosity] Looking for a tutorial

### ISSUE THREAD

**Issue by VinniciusJesus** [gskinnerTeam/flutter-wonderous-app#94]
Hello! First of all, sorry for my bad English... I'm not sure if I'm in the right place to ask this question.

I've been a Flutter developer for a long time, and I'm always following Gskinner's projects, I consider you my inspiration and the reference of the level I want to reach.

But I have difficulties in writing codes of this level, is there any tutorial like "How to program like the Gskinner team"?

**Comment by esDotDev** [comment]
No sorry, we don't have anything like that at the moment. The closest thing is probably our blog where we post various articles on different approaches etc: https://blog.gskinner.com/?s=flutter
