### ISSUE TITLE
Scrolling doesn't work on the main wonders screen on macOS

### ISSUE THREAD

**Issue by xster** [gskinnerTeam/flutter-wonderous-app#96]
Mouse wheel scrolls don't scroll the content. Works with trackpad

**Comment by asaarnak** [comment]
I have MX Master 3 mouse that has dedicated horizontal scroll wheel.
It works, but it's not perfect.
The bigger the screen the more you need to scroll for the page to switch.
When using full screen window QHD 2560x1440 then it's really hard to scroll to the next page.
When resizing window to smallest size then it's easy to scroll pages too fast and skip pages.

**Comment by esDotDev** [comment]
Scrolling does work using the SHIFT modifier, which is the default Flutter behavior. We have also added some physical next/prev btns.
