### ISSUE TITLE
Upper left menu button jump in discrete steps

### ISSUE THREAD

**Issue by xster** [gskinnerTeam/flutter-wonderous-app#97]
A bit odd that while resizing the main window, the upper left menu make quantized ~3px jumps as the window get larger or smaller. Seems like it could just be a smooth transition

**Comment by esDotDev** [comment]
This is expected and due to some dynamic padding sizes that we use within the app to help make the app responsive to larger device sizes. However it was primarily built for use with hand-held devices, and it might make sense to disable it for web/desktop platforms.
